### ISSUE TITLE
The definition of Maybe may be better

### ISSUE THREAD

**Issue by sgalal** [ice1000/Books#2]
`data Maybe a = Just a | Nothing` -> `data Maybe a = Nothing | Just a` (P8)

Maybe such `Maybe` is better?

**Comment by ice1000** [comment]
Can you give any reason?

**Comment by ice1000** [comment]
BTW I plan to publish a `v1.1` for Book 1. It's possible to have improvements.

**Comment by sgalal** [comment]
That is because in Haskell we could write something like `Nothing < Just 42` by simply using `deriving (Eq, Ord)`.

**Comment by ice1000** [comment]
Good reason! Could you please send a pull request (so you can become a contributor)?
